--create table Test1Table (id int, TextString  varchar(max))

create table Test1_TextData (ID INT identity(1,1), TextData varchar(max))

insert into Test1_TextData (TextData)
values ('30.14 NZD (28.542%) NZ001, Not Required-Use Accounting Treatment-83275:Wellington-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83275:Wellington (83275:Wellington), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE) ; 75.46 NZD (71.458%) NZ001, Not Required-Use Accounting Treatment-84472:Wellington Actuarial Consult-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 84472:Wellington Actuarial Consult (84472:Wellington Actuarial Consult), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE) '),
('30.14 NZD (28.542%) NZ001, Not Required-Use Accounting Treatment-83275:Wellington-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83275:Wellington (83275:Wellington), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE) ; 75.46 NZD (71.458%) NZ001, Not Required-Use Accounting Treatment-84472:Wellington Actuarial Consult-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 84472:Wellington Actuarial Consult (84472:Wellington Actuarial Consult), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE) '),
('23.82 NZD (66.667%) NZ001, Not Required-Use Accounting Treatment-83370:Invercargill-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83370:Invercargill (83370:Invercargill), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE) ; 11.91 NZD (33.333%) NZ001, Not Required-Use Accounting Treatment-83325:Ashburton-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83325:Ashburton (83325:Ashburton), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE) '),
('23.82 NZD (66.667%) NZ001, Not Required-Use Accounting Treatment-83370:Invercargill-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83370:Invercargill (83370:Invercargill), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE) ; 11.91 NZD (33.333%) NZ001, Not Required-Use Accounting Treatment-83325:Ashburton-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83325:Ashburton (83325:Ashburton), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE) '),
('39.68 NZD (66.667%) NZ001, Not Required-Use Accounting Treatment-83370:Invercargill-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83370:Invercargill (83370:Invercargill), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE) ; 19.84 NZD (33.333%) NZ001, Not Required-Use Accounting Treatment-83325:Ashburton-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83325:Ashburton (83325:Ashburton), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE) '),
('39.68 NZD (66.667%) NZ001, Not Required-Use Accounting Treatment-83370:Invercargill-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83370:Invercargill (83370:Invercargill), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE) ; 19.84 NZD (33.333%) NZ001, Not Required-Use Accounting Treatment-83325:Ashburton-Postage-Expensed-Postage, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 83325:Ashburton (83325:Ashburton), COMMOD: Postage (Postage), ACCT_TRT: Expensed (Expensed), WD_ITEM: Postage (POSTAGE) '),
('2461.42 AUD (59.849%) AU021, Not Required-Use Accounting Treatment-82905:Operations   National-General Office Supplies-Expensed-Office Supplies, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 82905:Operations   National (82905:Operations   National), COMMOD: General Office Supplies (General Office Supplies), ACCT_TRT: Expensed (Expensed), WD_ITEM: Office Supplies (OFFICE_SUPPLIES) ; 1,096.42 AUD (26.659%) AU021, Not Required-Use Accounting Treatment-82908:AU VIC Melbourne 80 Collins St-General Office Supplies-Expensed-Office Supplies, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 82908:AU VIC Melbourne 80 Collins St (82908:AU VIC Melbourne 80 Collins St), COMMOD: General Office Supplies (General Office Supplies), ACCT_TRT: Expensed (Expensed), WD_ITEM: Office Supplies (OFFICE_SUPPLIES) ; 277.43 AUD (6.746%) AU021, Not Required-Use Accounting Treatment-82911:AU WA Perth 28 The Esplande-General Office Supplies-Expensed-Office Supplies, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 82911:AU WA Perth 28 The Esplande (82911:AU WA Perth 28 The Esplande), COMMOD: General Office Supplies (General Office Supplies), ACCT_TRT: Expensed (Expensed), WD_ITEM: Office Supplies (OFFICE_SUPPLIES) ; 277.43 AUD (6.746%) AU021, Not Required-Use Accounting Treatment-82912:AU SA Adelaide 91 King William-General Office Supplies-Expensed-Office Supplies, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 82912:AU SA Adelaide 91 King William (82912:AU SA Adelaide 91 King William), COMMOD: General Office Supplies (General Office Supplies), ACCT_TRT: Expensed (Expensed), WD_ITEM: Office Supplies (OFFICE_SUPPLIES) '),
('2461.42 AUD (59.849%) AU021, Not Required-Use Accounting Treatment-82905:Operations   National-General Office Supplies-Expensed-Office Supplies, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 82905:Operations   National (82905:Operations   National), COMMOD: General Office Supplies (General Office Supplies), ACCT_TRT: Expensed (Expensed), WD_ITEM: Office Supplies (OFFICE_SUPPLIES) ; 1,096.42 AUD (26.659%) AU021, Not Required-Use Accounting Treatment-82908:AU VIC Melbourne 80 Collins St-General Office Supplies-Expensed-Office Supplies, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 82908:AU VIC Melbourne 80 Collins St (82908:AU VIC Melbourne 80 Collins St), COMMOD: General Office Supplies (General Office Supplies), ACCT_TRT: Expensed (Expensed), WD_ITEM: Office Supplies (OFFICE_SUPPLIES) ; 277.43 AUD (6.746%) AU021, Not Required-Use Accounting Treatment-82911:AU WA Perth 28 The Esplande-General Office Supplies-Expensed-Office Supplies, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 82911:AU WA Perth 28 The Esplande (82911:AU WA Perth 28 The Esplande), COMMOD: General Office Supplies (General Office Supplies), ACCT_TRT: Expensed (Expensed), WD_ITEM: Office Supplies (OFFICE_SUPPLIES) ; 277.43 AUD (6.746%) AU021, Not Required-Use Accounting Treatment-82912:AU SA Adelaide 91 King William-General Office Supplies-Expensed-Office Supplies, PROJ_ACT: Not Required (Not Required), EXP_TYPE: Use Accounting Treatment (Use Accounting Treatment), COSTCNTR: 82912:AU SA Adelaide 91 King William (82912:AU SA Adelaide 91 King William), COMMOD: General Office Supplies (General Office Supplies), ACCT_TRT: Expensed (Expensed), WD_ITEM: Office Supplies (OFFICE_SUPPLIES) ')

with CTE_XMLData (id, XMLData, XMLData1) as
	(select a.id, convert(xml,'<val>' + REPLACE( TextData, ',', '</val><val>' ) + '</val>') XMLData,
				  convert(xml,'<val>' + REPLACE( TextData, ':', '</val><val>' ) + '</val>') XMLData1
	from Test1_TextData a)
	SELECT distinct a.id, c.val as '4th and 5th Comma (,) From TextData column' , d.val as 'between 1st and 2nd colon (:)'
	from CTE_XMLData a
		cross apply 
		(select b.* from
			(SELECT 
				x.f.value( '.', 'VARCHAR(max)' ) AS val, ROW_NUMBER() OVER(ORDER BY (Select 0)) AS Row_Num
			FROM XMLData.nodes( '//val' ) x( f ) 
			
			) b where b.Row_Num = 5
		) c
		cross apply 
		(select b.* from
			(SELECT 
				x.f.value( '.', 'VARCHAR(max)' ) AS val, ROW_NUMBER() OVER(ORDER BY (Select 0)) AS Row_Num
			FROM XMLData1.nodes( '//val' ) x( f ) 
			
			) b where b.Row_Num = 2
		) d;


